export const DetailsData = [
    {
        Welcome:"Neo Dynamics Limited is An Indigenous custom Clearing and Freight Forwarding service. About Neo Dynamics Limited We are a Nigerian based custom clearing and Freight Forwarding company based in Lagos, Nigeria. With our Track record, we pride ourselves as one of the RELIABLE CLEARING SERVICE COMPANY  that delivers a prompt and professional services to our clients We are known for our quality assured import and export Freight Forwarding services and Transportation; Sea, Air, Rail and Road. Clearing cost is totally geared up to deliver to all its clients a very strong and complete service back up in terms of comprehensive logistics solutions. It has created a value-driven portfolio which has been further bolstered by building a support team of professionals, a national and international network and also a pro-active response and technology driven system. Today, it handles the clearing and forwarding of a variety of industrial import and export consignments. From loading at ports, unloading, dispatch, warehousing etc, it can handle and deliver consignments of every shape and size across national and international borders. At Sovereign Trust Global Concept, we strive to provide our customers with fastest and reliable services, which regularly exceed their expectations. Our systems and procedures support us in our aim of gaining a deep expertise in our customers’ industries and achieving total customer satisfaction. We provide the best Custom Clearance services in Lagos ports and port Harcourt.",
        Services:"At Neo Dynamics Limited, we strive to provide our customers with fastest and reliable services, which regularly exceed their expectations. Our systems and procedures support us in our aim of gaining a deep expertise in our customers’ industries and achieving total customer satisfaction. We provide the best Custom Clearance services in Lagos ports and port Harcourt.",
        ImportClearance:"Neo Dynamics Limited is one of the leading Customs Clearing Agents that smoothly handles customs clearing of import consignments across international ports.",
        ImportAndExport:"We are highly specialized and professional in delivering time bound clearance services with reference to import/export of goods & consignments across the world.",
        LogisticsConsultation:"The Logistics Consultants can assist you in deciding which processes or functions should be outsourced and can also assist you in selecting a suitable service provider.",
        Wharehousing: "The Logistics Consultants can assist whether you are looking to implement a new facility, expand an existing site, or maximize your assets.",
    }
]